version: 2.1

parameters:
  max_python_version:
    type: string
    default: "3.14"

jobs:
  lint:
    docker:
      - image: cimg/python:<< pipeline.parameters.max_python_version >>
    resource_class: small
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            python3 -m pip install --upgrade flake8 flake8-commas flake8-quotes
            python3 -m flake8 . --max-complexity=10 --max-line-length=160 --show-source --exclude __init__.py
  tests:
    docker:
      - image: cimg/python:<< pipeline.parameters.max_python_version >>

      - image: tools-ext-01.ccr.xdmod.org/xdmod:xdmod-data-main-dev
        name: xdmod-main-dev
        entrypoint:
          - /bin/bash
          - -c
          - >
            HOSTNAME=xdmod-main-dev openssl req -new
            -key /etc/pki/tls/private/localhost.key -x509 -sha256 -days 365
            -out /etc/pki/tls/certs/localhost.crt -config /root/openssl.cnf
            && cp /etc/pki/tls/certs/localhost.crt /usr/share/xdmod/html/
            && /root/bin/services start
            && tail -f /dev/null

      - image: tools-ext-01.ccr.xdmod.org/xdmod:xdmod-data-11.0-dev
        name: xdmod-11.0-dev
        entrypoint:
          - /bin/bash
          - -c
          - >
            HOSTNAME=xdmod-11.0-dev openssl req -new
            -key /etc/pki/tls/private/localhost.key -x509 -sha256 -days 365
            -out /etc/pki/tls/certs/localhost.crt -config /root/openssl.cnf
            && cp /etc/pki/tls/certs/localhost.crt /usr/share/xdmod/html/
            && /root/bin/services start
            && tail -f /dev/null

      - image: tools-ext-01.ccr.xdmod.org/xdmod:xdmod-data-11.0
        name: xdmod-11.0
        entrypoint:
          - /bin/bash
          - -c
          - >
            HOSTNAME=xdmod-11.0 openssl req -new
            -key /etc/pki/tls/private/localhost.key -x509 -sha256 -days 365
            -out /etc/pki/tls/certs/localhost.crt -config /root/openssl.cnf
            && cp /etc/pki/tls/certs/localhost.crt /usr/share/xdmod/html/
            && /root/bin/services start
            && tail -f /dev/null
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./tests/ci/scripts/run_tests.sh

workflows:
  lint:
    jobs:
      - lint
  tests:
    jobs:
      - tests
